/*"*************************************************************"*/
/*"FileName: RCRD_data.c"*/
/*"Author:    		Version :  "*/
/*"2019-08-08 10:30:25"*/
/*"Description: 事件记录模块对象列表定义"*/
/*"总字节数: 306          "*/
/*"Function List:                     "*/
/*"                                    "*/
/*"History:                           "*/
/*"<author> <time> <version > <desc>  "*/
/*"************************************************************"*/
#include "PlatForm.h"
#include "DataCenterSoftware\Code\message\MS_OBIS.h"
#include "App\message\FRMT_def.h"
#include "App\record\RCRD.h"
#include "RCRD_data.h"
const ST_BLK_DATA_ATTR stRcrdBlkDataList[] = 
 {////  
  {E_RCRD_CNT_BLK,(E_FILE_RCRD_DATA <<16)+RCRD_CNT_BLK_OFF,4,MAX_ALL_RCRD,0x05},
  {E_RCRD_CUR_CNT,(RAM)+(INT32U)0,4,MAX_ALL_RCRD,0x05},
  {E_RCRD_MAX_CNT,(RAM)+(INT32U)0,4,MAX_ALL_RCRD,0x05},
  {E_RCRD_CUR_VALUE,(RAM)+(INT32U)0,4,MAX_EVT_RCRD,0x05},
  {E_RCRD_TIME_STATUS,(RAM)+(INT32U)0,6,MAX_EVT_RCRD,0x0B},
  {E_MOUTH_BILLDAY,(E_FILE_RCRD_PARA <<16)+MOUTH_BILL_DATE_OFF,2,MON_BILL_DATE_NUM,0x22},
 };
const ST_SINGLE_DATA_ATTR stRcrdSingleDataList[] = 
 {  
  {PWR_DOWN_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+PWR_DOWN_ROAD_OFF,MAX_OAD_PWR_DOWN*4,0x05},
  {MTR_COVER_OPEN_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+MTR_COVER_OPEN_EVNT_ROAD_OFF,MAX_OAD_MTR_COVER_OPEN*4,0x05},
  {PRG_EVT_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+PRG_EVNT_ROAD_OFF,MAX_OAD_PRG_EVNT*4,0x05},
  {CLRMTR_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+MTR_CLR_ROAD_OFF,MAX_OAD_MTR_CLR*4,0x05},
  {EVNT_CLR_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+EVNT_CLR_ROAD_OFF,MAX_OAD_EVNT_CLR*4,0x05},
  {DAY_TBL_PRG_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+DAY_TBL_PRG_ROAD_OFF,MAX_OAD_DAY_TBL_PRG*4,0x05},
  {SEASON_TBL_PRG_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+SEASON_TBL_PRG_ROAD_OFF,MAX_OAD_SEASON_TBL_PRG*4,0x05},
  {WEEKEND_PRG_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+WEEKEND_PRG_EVNT_ROAD_OFF,MAX_OAD_WEEKEND_PRG_EVNT*4,0x05},
  {A_ENGY_COM_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+A_ENGY_COM_ROAD_OFF,MAX_OAD_A_ENGY_COM*4,0x05},
  {BILL_DAY_PRG_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+BILL_DAY_PRG_EVNT_ROAD_OFF,MAX_OAD_BILL_DAY_PRG*4,0x05},
  {JUSTTIME_EVT_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+JUST_TIME_ROAD_OFF,MAX_OAD_JUST_TIME*4,0x05},
  {RELAY_ERR_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+RELAY_ERR_ROAD_OFF,MAX_OAD_RELAY_ERR*4,0x05},
  {PWR_FAILURE_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+PWR_FAILURE_ROAD_OFF,MAX_OAD_PWR_FAILURE*4,0x05},
  {HOLIDAY_PRG_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+HOLIDAY_PRG_ROAD_OFF,MAX_OAD_HOLIDAY_PRG*4,0x05},
  {OVERCURR_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+OVER_CURR_ROAD_OFF,MAX_OAD_OVER_CURR*4,0x05},
  {RTC_ERR_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+RTC_ERR_ROAD_OFF,MAX_OAD_RTC_ERR*4,0x05},
  {MS_ERR_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+MS_ERR_ROAD_OFF,MAX_OAD_MS_ERR*4,0x05},
  {MMT_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+MMT_FRZ_ROAD_OFF,MAX_OAD_MMT_FRZ*8,0x05},
  {MIN_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+MIN_FRZ_ROAD_OFF,MAX_OAD_MIN_FRZ *8,0x05},
  {E_LD_TYPE1_PERIOD,(E_FILE_RCRD_PARA <<16)+RCRD_PARA_LD_PRD_OFF,2,0x0C},
  {HOUR_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+HOUR_FRZ_ROAD_OFF,MAX_OAD_HOUR_FRZ *8,0x05},
  {E_LD_TYPE2_PERIOD,(E_FILE_RCRD_PARA <<16)+RCRD_PARA_LD_T2_PRD_OFF,2,0x0C},
  {DAY_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+DAY_FRZ_ROAD_OFF,MAX_OAD_DAY_FRZ *8,0x05},
  {E_LD_TYPE3_PERIOD,(E_FILE_RCRD_PARA <<16)+RCRD_PARA_LD_T3_PRD_OFF,2,0x0C},
  {MOUTH_BILL_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+ENGY_BILL_ROAD_OFF,MAX_OAD_MOUTH_BILL_FRZ *8,0x05},
  {E_LD_TYPE4_PERIOD,(E_FILE_RCRD_PARA <<16)+RCRD_PARA_LD_T4_PRD_OFF,2,0x0C},
  {MOUTH_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+MON_FRZ_ROAD_OFF,MAX_OAD_MOUTH_FRZ *8,0x05},
  {E_LD_TYPE5_PERIOD,(E_FILE_RCRD_PARA <<16)+RCRD_PARA_LD_T5_PRD_OFF,2,0x0C},
  {SEASON_TBL_SW_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+YSLOT_SW_FRZ_ROAD_OFF,MAX_OAD_SEASON_TBL_SW_FRZ *8,0x05},
  {E_LD_TYPE6_PERIOD,(E_FILE_RCRD_PARA <<16)+RCRD_PARA_LD_T6_PRD_OFF,2,0x0C},
  {DAY_TBL_SW_FRZ_OBJ_LIST,(E_FILE_RCRD_PARA <<16)+DSLOT_SW_FRZ_ROAD_OFF,MAX_OAD_DAY_TBL_SW_FRZ *8,0x05},
  {E_LD_ST_TIME,(E_FILE_RCRD_PARA <<16)+(RCRD_PARA_LD_ST_TM_OFF + 1),4,0x2D},
  {E_TIME_STAMP,(RAM)+(INT32U)&mMinCnt,4,0x05},
  {E_OPER_CODE,(RAM)+(INT32U)&oprateCode[0],4,0x35},
  {E_FRZ_ST_TIME,(RAM)+(INT32U)&DCDataBuf[0],6,0x0B},
 };
const ST_ACTION_ATTR stRcrdActionList[] = 
 {  
     {E_RCRD_CLR,RCRD_ClrRecord},
     {E_RCRD_ADD_ONE_ROAD,0},
     {E_RCRD_TRIGGER_RCRD,RCRD_Trigger_Rcrd},
     {E_RCRD_ADD_MULT_ROAD,0},
     {E_RCRD_TIME_ADJUST,RCRD_Time_Adjust},
     {E_RCRD_DEL_ONE_ROAD,0},
     {E_RCRD_PD_ACTION,RCRD_Pd_Action},
     {E_RCRD_DEL_ALL_ROAD,0},
 };
const ST_FIXED_LIST_ATTR listTimeCode[] = 
 { 
  { E_SYS_TIME,0x0B},
 };
const ST_FIXED_LIST_ATTR listPrg10Id[] = 
 { 
  { E_PP_Program_OAD,0x27},
 };
const ST_FIXED_LIST_ATTR listPrgDSlot[] = 
 { 
  { E_SYS_TIME,0x0B},
  { E_PP_OAD,0x05},
  { E_PROG_DAY_TBL,0x17},
 };
const ST_FIXED_LIST_ATTR listClrEvtId[] = 
 { 
  { E_SYS_TIME,0x0B},
  { E_PP_OAD,0x05},
 };
const ST_FIXED_LIST_ATTR listPrgHoliday[] = 
 { 
  { E_SYS_TIME,0x0B},
  { E_PP_OAD,0x05},
  { E_PROG_HOLIDAY,0x15},
 };
const ST_FIXED_LIST_ATTR listFrzBufTime[] = 
 { 
  { E_FRZ_ST_TIME,0x0B},
 };
const ST_FIXED_LIST_ATTR listMntStTime[] = 
 { 
  { E_MNT_EVNT_TIME_S,0x0B},
 };
const ST_FIXED_LIST_ATTR listMntEndTime[] = 
 { 
  { E_MNT_EVNT_TIME_E,0x0B},
 };
const ST_FIXED_LIST_ATTR list2ActEngy[] = 
 { 
  { E_PA_ENGY,0x0E},
  { E_NA_ENGY,0x0E},
 };
const ST_FIXED_LIST_ATTR listLrType1[] = 
 { 
  { E_TIME_STAMP,0x05},
  { E_VOLT_LA,0x2E},
  { E_CURR_LA,0x2F},
  { E_FREQ,0x30},
  { E_ACTIVE_PWR,0x31},
  { E_REACTIVE_PWR,0x3B},
  { E_FACTOR,0x32},
  { E_PA_ENGY,0x37},
  { E_NA_ENGY,0x37},
  { E_R_ENGY_I,0x36},
  { E_R_ENGY_II,0x36},
  { E_R_ENGY_III,0x36},
  { E_R_ENGY_IV,0x36},
 };
const ST_FIXED_LIST_ATTR listLrType2[] = 
 { 
  { E_TIME_STAMP,0x05},
  { E_ACTIVE_PWR,0x31},
 };
const ST_FIXED_LIST_ATTR listLrType3[] = 
 { 
  { E_TIME_STAMP,0x05},
  { E_FACTOR,0x32},
 };
const ST_FIXED_LIST_ATTR listLrType4[] = 
 { 
  { E_TIME_STAMP,0x05},
  { E_PA_ENGY,0x37},
  { E_NA_ENGY,0x37},
 };
const ST_FIXED_LIST_ATTR listOperCode[] = 
 { 
  { E_OPER_CODE,0x35},
 };
const ST_FIXED_LIST_ATTR listLrType5[] = 
 { 
  { E_TIME_STAMP,0x05},
  { E_R_ENGY_I,0x36},
  { E_R_ENGY_II,0x36},
  { E_R_ENGY_III,0x36},
  { E_R_ENGY_IV,0x36},
 };
const ST_FIXED_LIST_ATTR list6eng[] = 
 { 
  { E_PA_ENGY,0x0E},
  { E_NA_ENGY,0x0E},
  { E_R_ENGY_I,0x34},
  { E_R_ENGY_II,0x34},
  { E_R_ENGY_III,0x34},
  { E_R_ENGY_IV,0x34},
 };
const ST_FELXOBJ_DATA_ATTR stDrvDataList[] = 
 {  
  {E_EVT_LST_START_NULL,&listTimeCode[0],&list2ActEngy[0],1,2},
  {E_EVTLST_CLRMTR,&listTimeCode[0],&list6eng[0],1,6},
  {E_EVTLST_PD_S,&listMntStTime[0],&list2ActEngy[0],1,2},
  {E_EVTLST_PD_E,&listMntEndTime[0],&list2ActEngy[0],1,2},
  {E_EVTLST_JUSTTIME_S,&listOperCode[0],&listTimeCode[0],1,1},
  {E_EVTLST_JUSTTIME_E,&listTimeCode[0],0,1,0},
  {E_EVTLST_MTR_COVER_OPEN_S,&listMntStTime[0],&list6eng[0],1,6},
  {E_EVTLST_MTR_COVER_OPEN_E,&listMntEndTime[0],&list6eng[0],1,6},
  {E_EVTLST_RELAY_ERR_S,&listMntStTime[0],0,1,0},
  {E_EVTLST_RELAY_ERR_E,&listMntEndTime[0],0,1,0},
  {E_EVTLST_SOSCILLATOR_ERR_S,&listTimeCode[0],0,1,0},
  {E_EVTLST_SYS_RST_S,&listTimeCode[0],0,1,0},
  {E_EVTLST_MGMT_ERR_S,&listTimeCode[0],&list2ActEngy[0],1,2},
  {E_EVTLST_MGMT_ERR_E,&listTimeCode[0],&list2ActEngy[0],1,2},
  {E_EVTLST_UPGRADE_S,&listTimeCode[0],0,1,0},
  {E_EVTLST_UPGRADE_E,&listTimeCode[0],0,1,0},
  {E_EVTLST_NOLEG_REPALCE_S,&listTimeCode[0],&list6eng[0],1,6},
  {E_EVTLST_NOLEG_REPALCE_E,&listTimeCode[0],&list6eng[0],1,6},
  {EVTLST_END,&listTimeCode[0],0,1,0},
  {E_EVTLST_PWR_FAILURE_S,&listMntStTime[0],0,1,0},
  {E_EVTLST_PWR_FAILURE_E,&listMntEndTime[0],0,1,0},
  {E_EVTLST_EVNT_CLR,&listClrEvtId[0],0,2,0},
  {E_EVTLST_RTC_ERR_S,&listTimeCode[0],0,1,0},
  {E_EVTLST_MS_ERR_S,&listTimeCode[0],0,1,0},
  {E_EVTLST_MS_ERR_E,&listTimeCode[0],0,1,0},
  {E_FRZ_LST_MON_FRZ,&listTimeCode[0],0,1,0},
  {E_FRZ_LST_MIN_FRZ,&listTimeCode[0],0,1,0},
  {E_FRZ_LST_HOUR_FRZ,&listTimeCode[0],0,1,0},
  {E_FRZ_LST_DAY_FRZ,&listFrzBufTime[0],0,1,0},
  {E_FRZ_LST_MOUTH_BILL_FRZ,&listFrzBufTime[0],0,1,0},
  {E_FRZ_LST_MOUTH_FRZ,&listTimeCode[0],0,1,0},
  {E_FRZ_LST_LR_TYPE1,&listLrType1[0],0,13,0},
  {E_FRZ_LST_LR_TYPE2,&listLrType2[0],0,2,0},
  {E_FRZ_LST_LR_TYPE3,&listLrType3[0],0,2,0},
  {E_FRZ_LST_LR_TYPE4,&listLrType4[0],0,3,0},
  {E_FRZ_LST_LR_TYPE5,&listLrType5[0],0,5,0},
 };
const ST_FILE_ATTR stFileDataList[] = 
 {  
  {E_PWR_DOWN_EVNT_RCRD,E_FILE_PWR_DOWN_EVNT,0,PWR_DOWN_SZ,E_EVTLST_PD_S,E_EVTLST_PD_E},
  {E_MTR_COVER_OPEN_EVNT_RCRD,E_FILE_MTR_COVER_OPEN_EVNT,0,MTR_COVER_OPEN_SZ,E_EVTLST_MTR_COVER_OPEN_S,E_EVTLST_MTR_COVER_OPEN_E},
  {E_MTR_CLR_EVNT_RCRD,E_FILE_MTR_CLR_EVNT,0,MTR_CLR_SZ,E_EVTLST_CLRMTR,0},
  {E_EVNT_CLR_EVNT_RCRD,E_FILE_EVNT_CLR_EVNT,0,EVNT_CLR_SZ,E_EVTLST_EVNT_CLR,0},
  {E_JUST_TIME_EVNT_RCRD,E_FILE_JUST_TIME_EVNT,0,JUST_TIME_SZ,E_EVTLST_JUSTTIME_S,E_EVTLST_JUSTTIME_E},
  {E_RELAY_ERR_EVNT_RCRD,E_FILE_RELAY_ERR_EVNT,0,RELAY_ERR_SZ,E_EVTLST_RELAY_ERR_S,E_EVTLST_RELAY_ERR_E},
  {E_PWR_FAILURE_EVNT_RCRD,E_FILE_PWR_FAILURE_EVNT,0,PWR_FAILURE_SZ,E_EVTLST_PWR_FAILURE_S,E_EVTLST_PWR_FAILURE_E},
  {E_OSCILLATOR_ERR_RCRD,E_FILE_OSCILLATOR_ERR_EVNT,0,OSCILLATOR_ERR_EVT_SZ,E_EVTLST_SOSCILLATOR_ERR_S,0},
  {E_MGMT_COMM_ERR_RCRD,E_FILE_MGMT_COMM_ERR_EVNT,0,MGMT_COMM_ERR_SZ,E_EVTLST_MGMT_ERR_S,E_EVTLST_MGMT_ERR_E},
  {E_SYS_RST_RCRD,E_FILE_SYS_RST_EVNT,0,SYS_RST_EVNT_SZ,E_EVTLST_SYS_RST_S,0},
  {E_RTC_ERR_EVNT_RCRD,E_FILE_RTC_ERR_EVNT,0,RTC_ERR_SZ,E_EVTLST_RTC_ERR_S,0},
  {E_NONLEGAL_UPGRADE_RCRD,E_FILE_UPGRADE_EVNT,0,UPGRADE_SZ,E_EVTLST_UPGRADE_S,E_EVTLST_UPGRADE_E},
  {E_NONLEGAL_REPLACE_RCRD,E_FILE_NOLEG_REPALCE_EVNT,0,NOLEG_REPALCE_SZ,E_EVTLST_NOLEG_REPALCE_S,E_EVTLST_NOLEG_REPALCE_E},
  {E_BROADCAST_JUST_TIME_RCRD,E_FILE_BROADCAST_JUST_TIME_EVNT,0,BROADCAST_JUST_TIME_SZ,E_EVTLST_JUSTTIME_S,E_EVTLST_JUSTTIME_E},
  {E_MS_ERR_EVNT_RCRD,E_FILE_MS_ERR_EVNT,0,MS_ERR_SZ,E_EVTLST_MS_ERR_S,E_EVTLST_MS_ERR_E},
  {E_EVT_END_RCRD,E_FILE_OVER_CURR_LA_EVNT,0,OVER_CURR_LA_SZ,0,0},
  {E_MMT_FRZ_RCRD,E_FILE_MMT_FRZ,0,MMT_FRZ_SZ,E_FRZ_LST_MON_FRZ,0},
  {E_MIN_FRZ_RCRD,E_FILE_MIN_FRZ,0,1,E_FRZ_LST_MIN_FRZ,0},
  {E_HOUR_FRZ_RCRD,E_FILE_HOUR_FRZ,0,HOUR_FRZ_SZ,E_FRZ_LST_HOUR_FRZ,0},
  {E_DAY_FRZ_RCRD,E_FILE_DAY_FRZ,0,DAY_FRZ_SZ,E_FRZ_LST_DAY_FRZ,0},
  {E_MONTH_BILL_FRZ_RCRD,E_FILE_MONTH_BILL_FRZ,0,MONTH_BILL_SZ,E_FRZ_LST_MOUTH_BILL_FRZ,0},
  {E_MONTH_FRZ_RCRD,E_FILE_MONTH_FRZ,0,MONTH_FRZ_SZ,E_FRZ_LST_MOUTH_FRZ,0},
  {E_LR_TYPE1_RCRD,E_FILE_MIN_FRZ,0,1,E_FRZ_LST_LR_TYPE1,0},
  {E_LR_TYPE2_RCRD,E_FILE_MIN_FRZ,0,1,E_FRZ_LST_LR_TYPE2,0},
  {E_LR_TYPE3_RCRD,E_FILE_MIN_FRZ,0,1,E_FRZ_LST_LR_TYPE3,0},
  {E_LR_TYPE4_RCRD,E_FILE_MIN_FRZ,0,1,E_FRZ_LST_LR_TYPE4,0},
  {E_STEP_BILL_FRZ_RCRD,E_FILE_DAY_TBL_SW_FRZ,0,DAY_TBL_SW_FRZ_SZ,0,0},
 };